// portfolio-content.ts
// Contenu bilingue FR/EN pour le portfolio de Yassine FENDI

export type CourseItem = {
  name: string;
  grade: string;
};

export type Achievement = {
  id: number;
  type: 'certification' | 'specialization' | 'production';
  title: string;
  description: string;
  icon: string;
  date: string;
  issuer?: string;
  courses?: CourseItem[];
  image?: string;
};

export const portfolioContent = {
  fr: {
    navigation: {
      about: 'À propos',
      experience: 'Expérience',
      skills: 'Compétences',
      projects: 'Projets',
      contact: 'Contact',
    },
    hero: {
      greeting: 'Bonjour, je suis',
      name: 'Yassine FENDI',
      title: 'Data Scientist & AI Engineer',
      subtitle: "Étudiant en Master Data Science & IA à DSTI et alternant chez Groupama. Passionné par l'intelligence artificielle, la data et l'ingénierie logicielle.",
      cta: 'Voir mes projets',
    },
    about: {
      title: 'À',
      subtitle: 'propos',
      heading: 'Développeur & Data Scientist passionné',
      description: [
        "Je suis actuellement en formation Applied MSc in Data Science & Artificial Intelligence à l'Institut DSTI et alternant en tant que Data Scientist chez Groupama.",
        "J'ai une solide expérience en développement full-stack et dans la création d'architectures Data & IA robustes et évolutives.",
      ],
      highlights: [
        { icon: 'Code2', label: 'Développement Full-Stack', color: 'text-blue-500' },
        { icon: 'Brain', label: 'Machine Learning & IA', color: 'text-purple-500' },
        { icon: 'Zap', label: 'Performance & Optimisation', color: 'text-yellow-500' },
        { icon: 'Sparkles', label: 'Génération de Valeur', color: 'text-green-500' },
      ],
    },
    skills: {
      title: 'Mes',
      subtitle: 'compétences',
      description: 'Un aperçu de mon expertise technique.',
      categories: [
        {
          title: 'Data Science & ML',
          gradient: 'from-blue-500 to-cyan-500',
          skills: [
            { name: 'Python', level: 95 },
            { name: 'Machine Learning', level: 90 },
            { name: 'Deep Learning', level: 85 },
            { name: 'GenAI / LLMs', level: 85 },
          ],
        },
        {
          title: 'Data Engineering',
          gradient: 'from-green-500 to-emerald-500',
          skills: [
            { name: 'SQL / PostgreSQL', level: 90 },
            { name: 'Airflow', level: 85 },
            { name: 'ETL Pipelines', level: 85 },
            { name: 'Qdrant / Vector DB', level: 80 },
          ],
        },
        {
          title: 'MLOps & Infrastructure',
          gradient: 'from-orange-500 to-red-500',
          skills: [
            { name: 'Docker', level: 85 },
            { name: 'CI/CD (GitLab)', level: 80 },
            { name: 'Linux / Bash', level: 80 },
            { name: 'Celery / Redis', level: 75 },
          ],
        },
        {
          title: 'Development',
          gradient: 'from-purple-500 to-pink-500',
          skills: [
            { name: 'Django / Flask', level: 90 },
            { name: 'React / TypeScript', level: 80 },
            { name: 'C/C++', level: 75 },
            { name: 'Git', level: 90 },
          ],
        },
      ],
      technologies: ['Scikit-learn', 'TensorFlow', 'PyTorch', 'FastAPI', 'MinIO', 'Neo4j', 'LangChain', 'Streamlit', 'Azure OpenAI', 'Dataiku'],
    },
    contact: {
      title: 'Me',
      subtitle: 'contacter',
      cta: 'Vous avez un projet en tête ou une opportunité ? Discutons-en !',
      message: "N'hésitez pas à m'envoyer un message via le formulaire ou directement par email.",
      info: [
        { label: 'Email', value: 'yassine.fendi@edu.dsti.institute' },
        { label: 'Phone', value: '+33 7 63 62 49 47' },
        { label: 'Location', value: 'Paris, France' },
      ],
      success: 'Message envoyé !',
      successMessage: 'Merci pour votre message. Je vous répondrai dans les plus brefs délais.',
      error: 'Erreur',
      errorMessage: "Une erreur est survenue lors de l'envoi du message. Veuillez réessayer.",
      sendButton: 'Envoyer le message',
    },
    experience: {
      title: 'Expérience',
      subtitle: 'Formation',
      description: 'Mon parcours en Data Science, IA et ingénierie logicielle',
      items: [
        {
          type: 'education' as const,
          title: 'Applied MSc in Data Science & Artificial Intelligence',
          company: 'Data ScienceTech Institute (DSTI)',
          location: 'Paris, France',
          period: '2024 – 2026',
          description: 'Master spécialisé couvrant le Machine Learning avancé, le Deep Learning, la GenAI et le déploiement de modèles en production.',
          technologies: ['Python', 'Machine Learning', 'Deep Learning', 'GenAI', 'MLOps'],
        },
        {
          type: 'work' as const,
          title: 'Data Scientist – Alternance',
          company: 'GGVIE – Groupe Groupama',
          location: 'Paris, France',
          period: 'Sept 2025 – Présent',
          description: "Développement de modèles ML en production (détection de fraude, scoring client), agent RAG conversationnel indexant +100 documents de sécurité, et agent MCP intégrant des webservices métier REST/SOAP.",
          technologies: ['Python', 'XGBoost', 'Isolation Forest', 'Qdrant', 'LLM', 'RAG', 'Django', 'Airflow', 'Docker', 'GitLab CI/CD', 'Azure OpenAI'],
        },
        {
          type: 'work' as const,
          title: 'Data Engineer Python – Stage',
          company: 'GGVIE – Groupe Groupama',
          location: 'Paris, France',
          period: 'Avr 2025 – Août 2025',
          description: "Mise en place d'un pipeline ETL automatisé (architecture Médaillon) sur la base SIREN orchestré via Airflow, et développement d'une application de prospection TNS ciblant 35 000 communes.",
          technologies: ['Python', 'Airflow', 'PostgreSQL', 'Flask', 'Streamlit', 'Docker', 'GitLab CI/CD'],
        },
        {
          type: 'education' as const,
          title: "Diplôme National d'Ingénieur – Informatique Industrielle & Automatique",
          company: 'INSAT',
          location: 'Tunis, Tunisie',
          period: '2019 – 2024',
          description: "Formation d'ingénieur en informatique industrielle, couvrant les systèmes embarqués, l'automatique, et le développement logiciel.",
          technologies: ['C/C++', 'Python', 'Java', 'SQL', 'Systèmes embarqués'],
        },
        {
          type: 'work' as const,
          title: 'Data Scientist – Stage',
          company: 'Axe Finance',
          location: 'Tunis, Tunisie',
          period: 'Juil 2023 – Août 2023',
          description: "Segmentation de 9 000 clients par clustering (K-means, DBSCAN, PCA) pour l'analyse de portefeuille et visualisation via une application Flask.",
          technologies: ['Python', 'SQL', 'Scikit-learn', 'K-means', 'DBSCAN', 'PCA', 'Flask'],
        },
      ],
    },
    projects: [
      {
        title: 'DataCopilot AI',
        description: "Plateforme data/IA full-stack no-code inspirée de Dataiku et n8n. Orchestration de pipelines data, Text-to-SQL en langage naturel et génération de dashboards no-code.",
        tech: ['Django', 'Celery', 'Redis', 'React', 'Qdrant', 'MinIO', 'Docker', 'CI/CD'],
        github: 'https://github.com/FendiYassine',
        live: '#',
        featured: true,
      },
      {
        title: 'Agent RAG RSSI',
        description: "Agent conversationnel RAG indexant +100 documents de politique de sécurité dans une base vectorielle Qdrant. Réponses tracées avec piste d'audit complète, déployé en production chez Groupama.",
        tech: ['Python', 'Qdrant', 'LLM', 'Django', 'Celery', 'Redis', 'MinIO', 'Docker'],
        github: '#',
        live: '#',
        featured: true,
      },
      {
        title: 'Détection de Fraude – Indemnités Journalières',
        description: "Modèle non supervisé Isolation Forest pour la détection de fraude aux indemnités journalières. En production, avec réduction du temps d'investigation de ~40% et mise à disposition des données au métier chaque fin de mois.",
        tech: ['Python', 'Isolation Forest', 'Dataiku', 'PostgreSQL', 'Airflow'],
        github: '#',
        live: '#',
        featured: true,
      },
      {
        title: 'Scoring de Risque Client',
        description: "Modèle supervisé XGBoost (AUC > 0.85) entraîné sur données assurantielles. En production, avec liste de clients prioritaires mise à disposition des équipes métier chaque fin de mois.",
        tech: ['Python', 'XGBoost', 'Scikit-learn', 'Dataiku', 'Airflow'],
        github: '#',
        live: '#',
        featured: true,
      },
      {
        title: 'Agent MCP Webservices Métier',
        description: "Agent conversationnel intégrant des webservices métier REST/SOAP via LLM pour les gestionnaires de contrats. Présenté au Club Data GGVIE.",
        tech: ['Django', 'React', 'LLM', 'REST/SOAP', 'Grafana'],
        github: '#',
        live: '#',
        featured: false,
      },
      {
        title: 'Pipeline ETL – Base SIREN',
        description: "Pipeline ETL automatisé (architecture Médaillon) traitant la base SIREN data.gouv via Airflow. Données mises à jour sans intervention manuelle pour les équipes risque et conformité.",
        tech: ['Python', 'Airflow', 'PostgreSQL', 'GitLab CI/CD', 'Docker'],
        github: '#',
        live: '#',
        featured: false,
      },
      {
        title: 'Application Prospection TNS',
        description: "Application de ciblage commercial de 35 000 communes, extraction SIRET et coordonnées TNS non-clients. Déployée en production chez Groupama.",
        tech: ['Python', 'PostgreSQL', 'Flask', 'Streamlit', 'Docker'],
        github: '#',
        live: '#',
        featured: false,
      },
      {
        title: 'Segmentation Client – Axe Finance',
        description: "Segmentation de 9 000 clients par clustering (K-means, DBSCAN, PCA) pour l'analyse de portefeuille, avec visualisation interactive via Flask.",
        tech: ['Python', 'SQL', 'Scikit-learn', 'Flask'],
        github: '#',
        live: '#',
        featured: false,
      },
    ],
    achievements: [
      {
        id: 1,
        type: 'production',
        title: 'Agent RAG en Production – Groupama',
        description: "Déploiement en production d'un agent RAG conversationnel RSSI indexant +100 documents de sécurité, avec piste d'audit complète, utilisé quotidiennement par les équipes métier.",
        icon: 'Trophy',
        date: '2026',
        issuer: 'GGVIE – Groupe Groupama',
      },
      {
        id: 2,
        type: 'certification',
        title: 'Neo4j Certified Professional',
        description: "Certification professionnelle attestant d'une maîtrise avancée des bases de données graphes Neo4j et du langage de requête Cypher, appliquée à des cas d'usage data complexes.",
        icon: 'Medal',
        date: 'Juin 2025',
        issuer: 'Neo4j',
        image: '/images/achievements/Neo4J certificate.png',
      },
      {
        id: 3,
        type: 'specialization',
        title: 'Deep Learning Specialization',
        description: "Programme fondateur en 5 cours couvrant les architectures de réseaux de neurones profonds (CNN, RNN, LSTM, Transformers), les stratégies d'entraînement avancées et les applications réelles : reconnaissance vocale, traitement du langage naturel et vision par ordinateur.",
        icon: 'Award',
        date: 'Fév 2024',
        issuer: 'DeepLearning.AI',
        courses: [
          { name: 'Neural Networks and Deep Learning', grade: '98%' },
          { name: 'Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization', grade: '92.80%' },
          { name: 'Structuring Machine Learning Projects', grade: '86.66%' },
          { name: 'Convolutional Neural Networks', grade: '98%' },
          { name: 'Natural Language Processing with Classification and Vector Spaces', grade: '100%' },
        ],
        image: 'images/achievements/Deep_learning_sepecialization.jpg'
      },
      {
        id: 4,
        type: 'specialization',
        title: 'Machine Learning Specialization',
        description: "Programme fondateur en 3 cours créé par DeepLearning.AI et Stanford Online, enseigné par Andrew Ng. Couvre l'apprentissage supervisé, non supervisé et les meilleures pratiques de l'industrie pour développer des modèles ML robustes.",
        icon: 'Star',
        date: 'Déc 2023',
        issuer: 'DeepLearning.AI & Stanford University',
        courses: [
          { name: 'Supervised Machine Learning: Regression and Classification', grade: '100%' },
          { name: 'Advanced Learning Algorithms', grade: '100%' },
          { name: 'Unsupervised Learning, Recommenders, Reinforcement Learning', grade: '98%' },
        ],
        image: 'images/achievements/Machine learnig spec.png'
      },
    ] as Achievement[],
  },

  en: {
    navigation: {
      about: 'About',
      experience: 'Experience',
      skills: 'Skills',
      projects: 'Projects',
      contact: 'Contact',
    },
    hero: {
      greeting: 'Hi, I am',
      name: 'Yassine FENDI',
      title: 'Data Scientist & AI Engineer',
      subtitle: 'Applied MSc in Data Science & AI student at DSTI and Data Scientist apprentice at Groupama. Passionate about artificial intelligence, data, and software engineering.',
      cta: 'View My Work',
    },
    about: {
      title: 'About',
      subtitle: 'me',
      heading: 'Passionate Developer & Data Scientist',
      description: [
        'I am currently pursuing an Applied MSc in Data Science & Artificial Intelligence at DSTI and working as a Data Scientist apprentice at Groupama.',
        'I have a strong background in full-stack development and building robust, scalable Data & AI architectures.',
      ],
      highlights: [
        { icon: 'Code2', label: 'Full-Stack Development', color: 'text-blue-500' },
        { icon: 'Brain', label: 'Machine Learning & AI', color: 'text-purple-500' },
        { icon: 'Zap', label: 'Performance & Optimization', color: 'text-yellow-500' },
        { icon: 'Sparkles', label: 'Value Generation', color: 'text-green-500' },
      ],
    },
    skills: {
      title: 'My',
      subtitle: 'skills',
      description: 'An overview of my technical expertise.',
      categories: [
        {
          title: 'Data Science & ML',
          gradient: 'from-blue-500 to-cyan-500',
          skills: [
            { name: 'Python', level: 95 },
            { name: 'Machine Learning', level: 90 },
            { name: 'Deep Learning', level: 85 },
            { name: 'GenAI / LLMs', level: 85 },
          ],
        },
        {
          title: 'Data Engineering',
          gradient: 'from-green-500 to-emerald-500',
          skills: [
            { name: 'SQL / PostgreSQL', level: 90 },
            { name: 'Airflow', level: 85 },
            { name: 'ETL Pipelines', level: 85 },
            { name: 'Qdrant / Vector DB', level: 80 },
          ],
        },
        {
          title: 'MLOps & Infrastructure',
          gradient: 'from-orange-500 to-red-500',
          skills: [
            { name: 'Docker', level: 85 },
            { name: 'CI/CD (GitLab)', level: 80 },
            { name: 'Linux / Bash', level: 80 },
            { name: 'Celery / Redis', level: 75 },
          ],
        },
        {
          title: 'Development',
          gradient: 'from-purple-500 to-pink-500',
          skills: [
            { name: 'Django / Flask', level: 90 },
            { name: 'React / TypeScript', level: 80 },
            { name: 'C/C++', level: 75 },
            { name: 'Git', level: 90 },
          ],
        },
      ],
      technologies: ['Scikit-learn', 'TensorFlow', 'PyTorch', 'FastAPI', 'MinIO', 'Neo4j', 'LangChain', 'Streamlit', 'Azure OpenAI', 'Dataiku'],
    },
    contact: {
      title: 'Contact',
      subtitle: 'me',
      cta: "Have a project in mind or an opportunity? Let's talk!",
      message: 'Feel free to send me a message using the form or directly via email.',
      info: [
        { label: 'Email', value: 'yassine.fendi@edu.dsti.institute' },
        { label: 'Phone', value: '+33 7 63 62 49 47' },
        { label: 'Location', value: 'Paris, France' },
      ],
      success: 'Message sent!',
      successMessage: 'Thank you for your message. I will get back to you as soon as possible.',
      error: 'Error',
      errorMessage: 'An error occurred while sending the message. Please try again.',
      sendButton: 'Send Message',
    },
    experience: {
      title: 'Experience',
      subtitle: 'Education',
      description: 'My journey in Data Science, AI and software engineering',
      items: [
        {
          type: 'education' as const,
          title: 'Applied MSc in Data Science & Artificial Intelligence',
          company: 'Data ScienceTech Institute (DSTI)',
          location: 'Paris, France',
          period: '2024 – 2026',
          description: 'Specialized master covering advanced Machine Learning, Deep Learning, GenAI and production model deployment.',
          technologies: ['Python', 'Machine Learning', 'Deep Learning', 'GenAI', 'MLOps'],
        },
        {
          type: 'work' as const,
          title: 'Data Scientist – Apprenticeship',
          company: 'GGVIE – Groupe Groupama',
          location: 'Paris, France',
          period: 'Sept 2025 – Present',
          description: 'Built production ML models (fraud detection, customer scoring), a RAG conversational agent indexing 100+ security policy documents, and an MCP agent integrating REST/SOAP business webservices.',
          technologies: ['Python', 'XGBoost', 'Isolation Forest', 'Qdrant', 'LLM', 'RAG', 'Django', 'Airflow', 'Docker', 'GitLab CI/CD', 'Azure OpenAI'],
        },
        {
          type: 'work' as const,
          title: 'Python Data Engineer – Internship',
          company: 'GGVIE – Groupe Groupama',
          location: 'Paris, France',
          period: 'Apr 2025 – Aug 2025',
          description: 'Built an automated ETL pipeline (Medallion architecture) on the SIREN database orchestrated via Airflow, and developed a TNS prospecting application targeting 35,000 municipalities.',
          technologies: ['Python', 'Airflow', 'PostgreSQL', 'Flask', 'Streamlit', 'Docker', 'GitLab CI/CD'],
        },
        {
          type: 'education' as const,
          title: 'National Engineering Degree – Industrial IT & Automation',
          company: 'INSAT',
          location: 'Tunis, Tunisia',
          period: '2019 – 2024',
          description: 'Engineering degree in industrial computing, covering embedded systems, automation, and software development.',
          technologies: ['C/C++', 'Python', 'Java', 'SQL', 'Embedded Systems'],
        },
        {
          type: 'work' as const,
          title: 'Data Scientist – Internship',
          company: 'Axe Finance',
          location: 'Tunis, Tunisia',
          period: 'Jul 2023 – Aug 2023',
          description: 'Segmented 9,000 customers using clustering (K-means, DBSCAN, PCA) for portfolio analysis, with results visualized through a Flask web application.',
          technologies: ['Python', 'SQL', 'Scikit-learn', 'K-means', 'DBSCAN', 'PCA', 'Flask'],
        },
      ],
    },
    projects: [
      {
        title: 'DataCopilot AI',
        description: 'Full-stack no-code data/AI platform inspired by Dataiku and n8n. Data pipeline orchestration, natural language Text-to-SQL and no-code dashboard generation.',
        tech: ['Django', 'Celery', 'Redis', 'React', 'Qdrant', 'MinIO', 'Docker', 'CI/CD'],
        github: 'https://github.com/FendiYassine',
        live: '#',
        featured: true,
      },
      {
        title: 'CISO RAG Agent',
        description: 'Conversational RAG agent indexing 100+ security policy documents into a Qdrant vector database. Responses tracked with full audit trail, deployed in production at Groupama.',
        tech: ['Python', 'Qdrant', 'LLM', 'Django', 'Celery', 'Redis', 'MinIO', 'Docker'],
        github: '#',
        live: '#',
        featured: true,
      },
      {
        title: 'Fraud Detection – Daily Allowances',
        description: 'Unsupervised Isolation Forest model for daily allowance fraud detection. In production, reducing investigation time by ~40% with data made available to business teams at the end of every month.',
        tech: ['Python', 'Isolation Forest', 'Dataiku', 'PostgreSQL', 'Airflow'],
        github: '#',
        live: '#',
        featured: true,
      },
      {
        title: 'Customer Risk Scoring',
        description: 'Supervised XGBoost model (AUC > 0.85) trained on insurance data. In production, with priority customer list made available to business teams at the end of every month.',
        tech: ['Python', 'XGBoost', 'Scikit-learn', 'Dataiku', 'Airflow'],
        github: '#',
        live: '#',
        featured: true,
      },
      {
        title: 'MCP Business Webservices Agent',
        description: 'Conversational agent integrating REST/SOAP business webservices via LLM for contract managers. Presented at the Groupama Data Club.',
        tech: ['Django', 'React', 'LLM', 'REST/SOAP', 'Grafana'],
        github: '#',
        live: '#',
        featured: false,
      },
      {
        title: 'ETL Pipeline – SIREN Database',
        description: 'Automated ETL pipeline (Medallion architecture) processing the data.gouv SIREN database via Airflow. Data updated without manual intervention for risk and compliance teams.',
        tech: ['Python', 'Airflow', 'PostgreSQL', 'GitLab CI/CD', 'Docker'],
        github: '#',
        live: '#',
        featured: false,
      },
      {
        title: 'TNS Prospecting Application',
        description: 'Commercial targeting application for 35,000 municipalities, extracting SIRET numbers and TNS non-client contacts. Deployed in production at Groupama.',
        tech: ['Python', 'PostgreSQL', 'Flask', 'Streamlit', 'Docker'],
        github: '#',
        live: '#',
        featured: false,
      },
      {
        title: 'Customer Segmentation – Axe Finance',
        description: 'Segmentation of 9,000 customers using clustering (K-means, DBSCAN, PCA) for portfolio analysis, with interactive visualization via Flask.',
        tech: ['Python', 'SQL', 'Scikit-learn', 'Flask'],
        github: '#',
        live: '#',
        featured: false,
      },
    ],
    achievements: [
      {
        id: 1,
        type: 'production',
        title: 'RAG Agent in Production – Groupama',
        description: 'Deployed a production CISO conversational RAG agent indexing 100+ security documents with full audit trail, used daily by business teams.',
        icon: 'Trophy',
        date: '2026',
        issuer: 'GGVIE – Groupe Groupama',
      },
      {
        id: 2,
        type: 'certification',
        title: 'Neo4j Certified Professional',
        description: 'Professional certification demonstrating advanced mastery of Neo4j graph databases and the Cypher query language, applied to complex data use cases.',
        icon: 'Medal',
        date: 'June 2025',
        issuer: 'Neo4j',
        image: '/images/achievements/Neo4J certificate.png',
      },
      {
        id: 3,
        type: 'specialization',
        title: 'Deep Learning Specialization',
        description: 'Foundational 5-course program covering deep neural network architectures (CNN, RNN, LSTM, Transformers), advanced training strategies, and real-world applications: speech recognition, NLP, and computer vision.',
        icon: 'Award',
        date: 'Feb 2024',
        issuer: 'DeepLearning.AI',
        courses: [
          { name: 'Neural Networks and Deep Learning', grade: '98%' },
          { name: 'Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization', grade: '92.80%' },
          { name: 'Structuring Machine Learning Projects', grade: '86.66%' },
          { name: 'Convolutional Neural Networks', grade: '98%' },
          { name: 'Natural Language Processing with Classification and Vector Spaces', grade: '100%' },
        ],
        image: 'images/achievements/Deep_learning_sepecialization.jpg'
      },
      {
        id: 4,
        type: 'specialization',
        title: 'Machine Learning Specialization',
        description: 'Foundational 3-course program by DeepLearning.AI and Stanford Online, taught by Andrew Ng. Covers supervised learning, unsupervised learning, and industry best practices for building robust ML models.',
        icon: 'Star',
        date: 'Dec 2023',
        issuer: 'DeepLearning.AI & Stanford University',
        courses: [
          { name: 'Supervised Machine Learning: Regression and Classification', grade: '100%' },
          { name: 'Advanced Learning Algorithms', grade: '100%' },
          { name: 'Unsupervised Learning, Recommenders, Reinforcement Learning', grade: '98%' },
        ],
        image: 'images/achievements/Machine learnig spec.png'
      },
    ] as Achievement[],
  },
};